on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Clone Submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: '0.58.3'

      - name: Build
        run: hugo

      - uses: chrislennon/action-aws-cli@v1.1

      - name: Upload S3
        run: |
            aws s3 sync public/ s3://sagebrushgis.com/ 
            aws s3 sync public/ s3://www.sagebrushgis.com/ 

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate Cache
        run: |
            aws cloudfront create-invalidation --distribution-id E3K5BGWIOBE43A --paths /index.html
            aws cloudfront create-invalidation --distribution-id E2HM033WC46BN3 --paths /index.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
