on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Clone Submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: '0.58.3'

      - name: Build
        run: hugo


      - uses: actions/checkout@v2
        with:
          repository: zmaillard/zmaillard.github.io
          token: ${{ secrets.GITHUB_REPO_TOKEN }}
          path: zmaillard.github.io

      - name: Copy Changes
        shell: bash
        run: cp -R ./public/* ./zmaillard.github.io/


      - name: Commit files
        run: |
          cd ./zmaillard.github.io/
          git config --local user.email "zmaillard@protonmail.com"
          git config --local user.name "Zach Maillard"
          git add .
          git commit -am "Updated Pages"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_REPO_TOKEN }}
